# Generated by Django 5.2.16 on 2026-08-20 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name_ar', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('sort_order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('challenge_ar', models.TextField(blank=True)),
                ('challenge_en', models.TextField(blank=True)),
                ('direction_ar', models.TextField(blank=True)),
                ('direction_en', models.TextField(blank=True)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('services_ar', models.CharField(blank=True, max_length=300)),
                ('services_en', models.CharField(blank=True, max_length=300)),
                ('cover_image', models.ImageField(upload_to='projects/covers/')),
                ('behance_url', models.URLField(blank=True, max_length=500)),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('seo_title_ar', models.CharField(blank=True, max_length=180)),
                ('seo_title_en', models.CharField(blank=True, max_length=180)),
                ('seo_description_ar', models.CharField(blank=True, max_length=320)),
                ('seo_description_en', models.CharField(blank=True, max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.category')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('alt_ar', models.CharField(blank=True, max_length=240)),
                ('alt_en', models.CharField(blank=True, max_length=240)),
                ('layout_type', models.CharField(choices=[('full', 'Full width'), ('half', 'Half width'), ('portrait', 'Portrait'), ('landscape', 'Landscape'), ('grid', 'Grid')], default='full', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'abstract': False,
            },
        ),
    ]
