# Generated by Django 5.2.16 on 2026-08-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(default='محمد هشام', max_length=120)),
                ('name_en', models.CharField(default='Mohamed Hesham', max_length=120)),
                ('headline_ar', models.CharField(default='مصمم جرافيك يحوّل الأفكار إلى تجارب بصرية مؤثرة.', max_length=240)),
                ('headline_en', models.CharField(default='Graphic Designer creating visual experiences that make brands stand out.', max_length=240)),
                ('description_ar', models.TextField(default='مصمم جرافيك بخبرة تتجاوز 4 سنوات في تصميم الهويات البصرية ومحتوى السوشيال ميديا والحملات التسويقية والتصميمات الرقمية والمطبوعة.')),
                ('description_en', models.TextField(default='Graphic Designer with over 4 years of experience creating visually compelling work across digital and print platforms.')),
                ('badge_ar', models.CharField(default='متاح للمشاريع والتعاون', max_length=120)),
                ('badge_en', models.CharField(default='Available for projects and collaborations', max_length=120)),
                ('about_ar', models.TextField(default='أصنع حلولًا بصرية واضحة ومتسقة تساعد العلامات التجارية على الظهور والتواصل بثقة.')),
                ('about_en', models.TextField(default='I create clear, consistent visual solutions that help brands stand out and communicate with confidence.')),
                ('years_experience', models.PositiveSmallIntegerField(default=4)),
                ('show_volunteering', models.BooleanField(default=True)),
                ('show_education', models.BooleanField(default=True)),
                ('show_certificates', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='Mohamed Hesham', max_length=120)),
                ('role_ar', models.CharField(default='مصمم جرافيك', max_length=120)),
                ('role_en', models.CharField(default='Graphic Designer', max_length=120)),
                ('email', models.EmailField(default='eng.mo.hesham22@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+20 127 559 3580', max_length=40)),
                ('whatsapp', models.CharField(default='201275593580', max_length=40)),
                ('location_ar', models.CharField(default='المنصورة، مصر', max_length=160)),
                ('location_en', models.CharField(default='Mansoura, Egypt', max_length=160)),
                ('logo', models.ImageField(blank=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, upload_to='branding/')),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile/')),
                ('default_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=2)),
                ('default_title_ar', models.CharField(default='محمد هشام | مصمم جرافيك', max_length=180)),
                ('default_title_en', models.CharField(default='Mohamed Hesham | Graphic Designer', max_length=180)),
                ('default_description_ar', models.TextField(default='مصمم جرافيك متخصص في الهويات البصرية والسوشيال ميديا والتصميم الرقمي والمطبوع.')),
                ('default_description_en', models.TextField(default='Graphic Designer specializing in branding, social media, digital and print design.')),
                ('keywords', models.CharField(blank=True, max_length=300)),
                ('open_graph_image', models.ImageField(blank=True, upload_to='seo/')),
                ('animation_intensity', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('show_cursor', models.BooleanField(default=True)),
                ('show_grid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('short_code', models.CharField(blank=True, max_length=3)),
                ('icon', models.ImageField(blank=True, upload_to='skills/')),
                ('kind', models.CharField(choices=[('software', 'Creative software'), ('professional', 'Professional')], default='professional', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('orbit_number', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Orbit 1'), (2, 'Orbit 2'), (3, 'Orbit 3')], default=0)),
                ('orbit_speed', models.PositiveSmallIntegerField(default=24)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('platform', models.CharField(max_length=60)),
                ('url', models.URLField(max_length=500)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'abstract': False,
            },
        ),
    ]
