# Generated by Django 5.2.16 on 2026-08-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title_ar', models.CharField(max_length=180)),
                ('title_en', models.CharField(max_length=180)),
                ('organization_ar', models.CharField(blank=True, max_length=180)),
                ('organization_en', models.CharField(blank=True, max_length=180)),
                ('year', models.PositiveIntegerField()),
                ('certificate_image', models.ImageField(blank=True, upload_to='certificates/images/')),
                ('certificate_pdf', models.FileField(blank=True, upload_to='certificates/pdfs/')),
                ('verification_url', models.URLField(blank=True, max_length=500)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('title_ar', models.CharField(max_length=240)),
                ('title_en', models.CharField(max_length=240)),
                ('institution_ar', models.CharField(blank=True, max_length=180)),
                ('institution_en', models.CharField(blank=True, max_length=180)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'abstract': False,
            },
        ),
    ]
