# Generated by Django 5.2.16 on 2026-08-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('company', models.CharField(max_length=180)),
                ('position_ar', models.CharField(max_length=180)),
                ('position_en', models.CharField(max_length=180)),
                ('location_ar', models.CharField(blank=True, max_length=180)),
                ('location_en', models.CharField(blank=True, max_length=180)),
                ('employment_type', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('company_logo', models.ImageField(blank=True, upload_to='experience/')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('organization', models.CharField(max_length=180)),
                ('role_ar', models.CharField(max_length=180)),
                ('role_en', models.CharField(max_length=180)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'abstract': False,
            },
        ),
    ]
