# Generated by Django 5.2.16 on 2026-08-20 07:49

import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to='library/%Y/%m/', validators=[media_library.models.validate_media])),
                ('alt_ar', models.CharField(blank=True, max_length=240)),
                ('alt_en', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
